plugins:
  nntp_bridge_enabled:
    default: true
    client: true
  nntp_bridge_override_title_validations:
    default: true
    client: true
  nntp_bridge_guest_username:
    default: system
    type: username
    client: true
  nntp_bridge_guest_notice:
    default: "*Post from NNTP guest {author}*"
    client: true
  nntp_bridge_dethreaded_notice:
    default: "*This post was de-threaded from NNTP. Discourse tried to guess where it belongs, but this may not be correct.*"
    client: true
  nntp_bridge_empty_body_replacement:
    default: "*(empty body from NNTP)*"
    client: true
  nntp_bridge_invalid_body_replacement:
    default: "*(invalid body from NNTP)*"
    client: true
  nntp_bridge_nntp_user_agent:
    default: Discourse NNTP Bridge
    client: true
  nntp_bridge_default_newsgroup:
    default: general
    client: true
